NUMBER_MAP = {'eka': '1', 'xvi': '2', 'wri': '3', 'cawura': '4', 'paFcan': '5', 'RaR': '6', 'sapwan': '7',
 'aRtan': '8', 'navan': '9', 'xaSan': '10', 'ekAxaSa': '11', 'xvAxaSa': '12', 'wrayoxaSa': '13', 'cawurxaSa': '14', 
 'paFcaxaSa': '15', 'RodaSa': '16', 'sapwaxaSa': '17', 'aRtAxaSa': '18', 'navaxaSa': '19', 'ekonaviMSawi': '19', 'viMSawi': '20', 
 'ekaviMSawi': '21', 'xvAviMSawi': '22', 'wrayoviMSawi': '23', 'cawurviMSawi': '24', 'paFcaviMSawi': '25', 'RadviMSawi': '26', 
 'sapwaviMSawi': '27', 'aRtAviMSawi': '28', 'navaviMSawi': '29', 'ekonawriMSaw': '29', 'wriMSaw': '30', 'ekawriMSaw': '31', 
 'xvAwriMSaw': '32', 'wrayaswriSaw': '33', 'cawuswriSaw': '34', 'paFcawriMSaw': '35', 'RatwriMSaw': '36', 'sapwawriMSaw': '37', 
 'aRtAwriMSaw': '38', 'navawriMSaw': '39', 'ekonacawvAriMSaw': '39', 'cawvAriMSaw': '40', 'ekacawvAriMSaw': '41', 'xvicawvAriMSaw': '42', 
 'xvAcawvAriMSaw': '42', 'wricawvAriMSaw': '43', 'wrayaScawvAriMSaw': '43', 'cawuScawvAriMSaw': '44', 'paFcacawvAriMSaw': '45', 
 'patcawvAriMSaw': '46', 'sapwacawvAriMSaw': '47', 'aRtacawvAriMSaw': '48', 'aRtAcawvAriMSaw': '48', 'navacawvAriMSaw': '49', 
 'ekonapaFcASaw': '49', 'paFcASaw': '50', 'ekapaFcASaw': '51', 'xvipaFcASaw xvApaFcASaw': '52', 'wripaFcASaw wrayaHpaFcASaw': '53', 
 'cawuHpaFcASaw': '54', 'paFcapaFcASaw': '55', 'RatpaFcASaw': '56', 'sapwapaFcASaw': '57', 'aRtApaFcASaw': '58', 'aRtapaFcASaw': '58',
 'navapaFcASaw': '59', 'ekonaRaRti': '59', 'RaRti': '60', 'ekaRaRti': '61', 'xviRaRti': '62', 'xvARaRti': '62', 'wriRaRti': '63', 
 'wrayaHRaRti': '63', 'cawuHRaRti': '64', 'paFcaRaRti': '65', 'RatRaRti': '66', 'sapwaRaRti': '67', 'aRtaRati': '68', 'aRtARaRti': '68', 
 'navaRaRti': '69', 'ekonasapwawi': '69', 'sapwawi': '70', 'ekasapwawi': '71', 'xvisapwawi': '72', 'xvAsapwawi': '72',
 'wrisapwawi': '73', 'wrayaHsapwawi': '73', 'cawuHsapwawi': '74', 'paFcasapwawi': '75', 'Ratsapwawi': '76', 'sapwasapwawi': '77', 
 'aRtasapwawi': '78', 'aRtAsapwawi': '78', 'navasapwawi': '79', 'ekonASIwi': '79', 'aSIwi': '80', 'ekASIwi': '81', 
 'xvayaSIwi': '82', 'wryaSIwi': '83', 'cawuraSIwi': '84', 'paFcASIwi': '85', 'RadaSIwi': '86', 'sapwASIwi': '87', 
 'aRtASIwi': '88', 'navASIwi': '89', 'ekonanavawi': '89', 'navawi': '90', 'ekanavawi': '91', 'xvinavawi': '92', 'xvAnavawi': '92',
 'wrinavawi': '93', 'wrayAMnavawi': '93', 'cawurnavawi': '94', 'paFcanavawi': '95', 'RaNNavawi': '96', 'sapwanavawi': '97', 'aRtanavawi': '98', 
 'aRtAnavawi': '98', 'navanavawi': '99', 'ekonaSawam': '99', 'Sawam': '100'}
